// vars/ciSetup.groovy
import groovy.json.JsonOutput

def call(Map config) {
  def language = (config.language ?: 'javascript').toLowerCase()
  echo "Injecting CI configuration files for a '${language}' project..."

  def gitAssets = ["CHANGELOG.md"]
  if (language == 'javascript') {
    if (fileExists('package.json')) {
      gitAssets << "package.json"
      if (fileExists('package-lock.json')) gitAssets << "package-lock.json"
      if (fileExists('yarn.lock')) gitAssets << "yarn.lock"
    }
  } else if (language == 'go') {
    if (fileExists('go.mod')) gitAssets << "go.mod"
    if (fileExists('go.sum')) gitAssets << "go.sum"
  } else if (language == 'python') {
    if (fileExists('requirements.txt')) gitAssets << "requirements.txt"
    if (fileExists('pyproject.toml')) gitAssets << "pyproject.toml"
  }

  def releaseConfigJs = """
// Auto-generated by CI setup
function normalize(name) {
  if (!name) return null;
  return name.replace(/^origin\\//, '');
}
function duo(name, pre) {
  const n = normalize(name);
  if (!n) return [];
  const short = pre ? { name: n, prerelease: pre } : n;
  const full  = pre ? { name: `origin/\${n}`, prerelease: pre } : `origin/\${n}`;
  return [short, full];
}
function parseBranches(env) {
  const spec = (env.SR_BRANCHES || '').trim();
  const cur  = normalize(env.BRANCH_NAME || env.GIT_BRANCH || 'main');
  if (!spec) return [cur];
  const out = [];
  spec.split(',').map(s => s.trim()).filter(Boolean).forEach(token => {
    const [name, pre] = token.split(':');
    out.push(...duo(name, pre));
  });
  if (out.length === 0) out.push(cur);
  return out;
}

const lang = (process.env.SR_LANG || '${language}').toLowerCase();

const basePlugins = [
  ['@semantic-release/commit-analyzer', {
    preset: 'conventionalcommits',
    releaseRules: [
      { breaking: true, release: 'major' },
      { type: 'feat',  release: 'minor' },
      { type: 'fix',   release: 'patch' },
      { type: 'perf',  release: 'patch' },
      { type: 'revert', release: 'patch' }
    ]
  }],
  '@semantic-release/release-notes-generator',
  ['@semantic-release/changelog', { changelogFile: 'CHANGELOG.md' }]
];

let gitAssets = ${JsonOutput.toJson(gitAssets)};

const tailPlugins = [
  ['@semantic-release/git', {
    assets: gitAssets,
    message: 'chore(release): \${nextRelease.version} [skip ci]\\n\\n\${nextRelease.notes}'
  }]
];

module.exports = {
  branches: parseBranches(process.env),
  plugins: [...basePlugins, ...tailPlugins]
};
""".stripIndent()

  writeFile file: 'release.config.js', text: releaseConfigJs
  echo "release.config.js created with assets: ${gitAssets}"

  // Validation: ensure we didn't accidentally mess up other tracked files
  def dirtyTracked = sh(
    script: '''#!/bin/bash
      set -e
      git status --porcelain | awk '{print $2}' | grep -v '^release.config.js$' || true
    ''',
    returnStdout: true
  ).trim()

  if (dirtyTracked) {
    error "[CI Setup ERROR] CI modified tracked repository files: ${dirtyTracked}"
  }

  echo 'CI configuration files injected successfully.'
}